spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:jtds:sqlserver://192.168.0.218:1433/ebiz4u
    username: ebiz4u
    password: ghkfWkr
    test-on-borrow: true
    validation-query: SELECT 1
    
logging:
  path: d:/deployed/enio/enio-api/logs/
  
enio:
  ftp:
    host: 192.168.0.218
    port: 21
    user: ebiz4u_ftp
    password: ebiz4u_ftp
  file:
    temp-dir: d:/deployed/enio/enio-api/temp/