spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:jtds:sqlserver://10.65.29.111/ebiz4u
    username: ebiz4u
    password: pcm1105
    test-on-borrow: true
    validation-query: SELECT 1
    
logging:
  path: c:/deployed/enio/enio-api/logs/
  
enio:
  ftp:
    host: 10.64.29.12
    port: 21
    user: ebiz4u_ftp
    password: ebiz4u_ftp1111
  file:
    temp-dir: c:/deployed/enio/enio-api/temp/